### ISSUE TITLE
Question: How to link to assets in post subfolder, like when using :imagesdir: ?

### ISSUE THREAD

**Issue by RichardJECooke** [hcoona/hexo-renderer-asciidoc#9]
I have a blog post written as an .adoc with my `:imagesdir:` set to blank (because the Hexo blogging system sets the post's relative url to the asset subfolder).

All my images load correctly, that's great. E.g.
```
image::patcher.png[]
```

But when I try to link to another file in my post's folder like
```
link:++animation.blend++[Blender project file]
```
the link is provided from the root of my site (incorrect).

How do I specify the root post folder for asset files, like I do the imagesdir folder for images please?

---

Raw HTML works, like
```
++++
<a href='animation.blend'>Blender project file</a>
++++
```
but I was hoping there's a more elegant way

**Comment by ggrossetie** [comment]
I believe that this issue is about resolving assets in Hexo. 
This plugin could dynamically define an attribute (for instance `assetsdir`):

```
link:{assetsdir}/animation.blend[Blender project file]
```

Or it could reimplement the path resolution on the link macro.

I think you should edit the question's title on Stackoverflow because it has nothing to do with Asciidoctor.js: https://stackoverflow.com/questions/52682485/whats-the-equivalent-of-imagesdir-for-other-asset-files-in-asciidoctor-js
